dist: bionic

language: node_js

matrix:
  include:
    - node_js: 10
    - node_js: 12
    - node_js: 14

addons:
  sonarcloud:
    organization: "chubbyjs"

git:
  depth: false

before_install:
  - export TZ=Europe/Zurich

script:
  - npm run build
  - npm run cs
  - npm test -- --coverage --no-cache
  - npm run infection

after_success:
  - coveralls < coverage/lcov.info
  - sonar-scanner
